easy_admin:
  entities:
    SurveyAnswerList:
      class: App\Entity\SurveyAnswerList
      permissions:
        list: ["ROLE_MANAGEUR"]
        edit: ["ROLE_MANAGEUR"]
        new: ["ROLE_MODERATEUR"]
        delete: ["ROLE_ADMIN"]
        show: ["ROLE_ADMIN"]
      list:
        title: "Liste de réponses possibles pour les sondages"
        actions:
          [
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
            { name: "new", label: "Ajouter" },
          ]
        fields:
          [
            { property: "createdBy", label: "Créer par" },
            { property: "answer", label: "Réponse" },
          ]
      form:
        title: "Ajouter/Modifier"
        fields: [{ property: "answer", label: "Réponse" }]
