twig:
    default_path: "%kernel.project_dir%/templates"
    globals:
        # Variables
        server_name: "%server.name%"
        site_copyright: "%site.copyright%"
        twitter_link: "%twitter.link%"
        youtube_link: "%youtube.link%"
        discord_link: "%discord.link%"
        # Service
        user_service: "@user_service"
        maintenance_service: "@maintenance_service"
        # Google Recaptcha v3
        RECAPTCHA3_SITE_KEY: "%env(RECAPTCHA3_SITE_KEY)%"