easy_admin:
  design:
    menu:
      - label: "Utilisateurs"
        icon: "users-cog"
        permission: "ROLE_MANAGEUR"
        children:
          [
            { entity: "User", label: "Joueurs" },
            { entity: "UserIp", label: "Historique IPs" },
          ]
      - label: "Maintenance"
        icon: "tools"
        permission: "ROLE_ADMIN"
        children:
          [
            {
              entity: "DevProgression",
              label: "Progressions",
              permission: "ROLE_ADMIN",
            },
          ]
      - label: "Forum"
        icon: "comments"
        permission: "ROLE_STAFF"
        children:
          [
            {
              entity: "ForumCategory",
              label: "Categories",
              permission: "ROLE_MANAGEUR",
            },
            {
              entity: "ForumSubCategory",
              label: "Sous-categories",
              permission: "ROLE_MANAGEUR",
            },
            { entity: "ForumDiscussion", label: "Discussions" },
            { entity: "ForumDiscussionAnswer", label: "Réponses" },
            {
              entity: "ForumDiscussionStatus",
              label: "Status",
              permission: "ROLE_MANAGEUR",
            },
          ]
      - label: "Sondages"
        icon: "poll-h"
        permission: "ROLE_STAFF"
        children:
          [
            {
              entity: "Survey",
              label: "Sondages",
              permission: "ROLE_MANAGEUR",
            },
            {
              entity: "SurveyAnswers",
              label: "Réponses",
              permission: "ROLE_MANAGEUR",
            },
            { entity: "SurveyComments", label: "Commentaires" },
            {
              entity: "SurveyAnswerList",
              label: "Listes réponses",
              permission: "ROLE_MANAGEUR",
            },
          ]
      - label: "Boutique"
        icon: "store"
        permission: "ROLE_ADMIN"
        children:
          [
          {
            entity: "StoreCategory",
            label: "Catégories",
            permission: "ROLE_ADMIN",
          },
          {
            entity: "StoreArticle",
            label: "Articles",
            permission: "ROLE_ADMIN",
          },
          ]
      - label: "Spoils"
        icon: "question"
        permission: "ROLE_STAFF"
        children:
          [
            { entity: "Spoil", label: "Spoils", permission: "ROLE_MANAGEUR" },
            { entity: "SpoilShare", label: "Partages", permission: "ROLE_MANAGEUR" },
            { entity: "SpoilGoalType", label: "Objectifs", permission: "ROLE_MANAGEUR" },
          ]
      - label: "Équipe"
        icon: "user-tie"
        permission: "ROLE_MANAGEUR"
        children:
          [
            { entity: "Staff", label: "Staff", permission: "ROLE_ADMIN" },
            {
              entity: "Thanks",
              label: "Remerciements",
              permission: "ROLE_MANAGEUR",
            },
            {
              entity: "StaffCategory",
              label: "Staff catégories",
              permission: "ROLE_ADMIN",
            },
            {
              entity: "ThanksCategory",
              label: "Remerciements catégories",
              permission: "ROLE_MANAGEUR",
            },
          ]
      - label: "Réseaux sociaux"
        icon: "network-wired"
        permission: "ROLE_ADMIN"
        children:
          [
          {
            entity: "SocialmediaType",
            label: "Liste",
            permission: "ROLE_ADMIN",
          },
          {
            entity: "MySocialmedia",
            label: "ScandiCraft",
            permission: "ROLE_ADMIN",
          },
          ]
      - label: "Votes"
        icon: "check-circle"
        permission: "ROLE_MANAGEUR"
        children:
          [
            { entity: "UserVote", label: "Votes", permission: "ROLE_MANAGEUR" },
            { entity: "VoteSite", label: "Sites de vote", permission: "ROLE_ADMIN" },
          ]
      - label: "Aide"
        icon: "hands-helping"
        permission: "ROLE_STAFF"
        children: [{ entity: "FAQ", label: "FAQ", permission: "ROLE_STAFF" }]
      - label: "Payments"
        icon: "money"
        permission: "ROLE_ADMIN"
        children:
          [
          {
            entity: "PaymentTypes",
            label: "Types",
            permission: "ROLE_ADMIN",
          },
          ]
      - label: "Logs"
        icon: "history"
        permission: "ROLE_ADMIN"
        children:
          [
            { entity: "ActionLog", label: "Actions", permission: "ROLE_ADMIN" },
            {
              entity: "ExceptionLog",
              label: "Exceptions",
              permission: "ROLE_ADMIN",
            },
          ]
      - { label: "liens" }
      - {
          label: "Retour",
          url: "/",
          icon: "chevron-circle-left",
          target: "_self",
        }
    assets:
      css:
        - "build/easy_admin.css"
  list:
    max_results: 50
  formats:
    datetime: "d/m/Y à H:i"
    date: d/m/Y
    time: "H:i"
    number: "%.3f"
