imports:
- { resource: User.yaml }
- { resource: DevProgression.yaml }
- { resource: Survey.yaml }
- { resource: SurveyAnswerList.yaml }
- { resource: SurveyAnswers.yaml }
- { resource: Thanks.yaml }
- { resource: ThanksCategory.yaml }
- { resource: SocialmediaType.yaml }
- { resource: MySocialmedia.yaml }