easy_admin:
  entities:
    DevProgression:
      class: App\Entity\DevProgression
      disabled_actions: ["show"]
      list:
        title: "Liste des maintenances"
        actions:
          [
            { name: "new", label: "Ajouter une maintenance" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "nom", label: "Nom" },
            { property: "pourcentage", label: "Pourcentage", template: "easy_admin/fields/pourcentage.html.twig" },
            { property: "under_maintenance", label: "En maintenance ?" },
          ]
      form:
        title: "Modifier la maintenance"
        fields:
          [
            { property: "nom", label: "Nom" },
            { property: "pourcentage", label: "Pourcentage" },
            { property: "under_maintenance", label: "En maintenance ?" },
          ]
      new:
        title: "Créer une maintenance"
