easy_admin:
  entities:
    MySocialmedia:
      class: App\Entity\MySocialmedia
      permissions:
        list: ["ROLE_ADMIN"]
        new: ["ROLE_ADMIN"]
        edit: ["ROLE_ADMIN"]
        delete: ["ROLE_ADMIN"]
        show: ["ROLE_ADMIN"]
      list:
        title: "Liste des résaux sociaux de ScandiCraft"
        actions:
          [
            { name: "new", label: "Ajouter" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "url", label: "Lien" },
            { property: "socialmedia_type", label: "Type" },
          ]
      form:
        title: "Ajouter/Modifier"
        fields:
          [
            { property: "url", label: "Lien" },
            {
              property: "socialmedia_type",
              label: "Type",
              type: "entity",
              type_options: { class: 'App\Entity\SocialmediaType' },
            },
          ]
