easy_admin:
  entities:
    Staff:
      class: App\Entity\Staff
      list:
        title: "Liste des membres du Staff"
        actions:
          [
            { name: "new", label: "Ajouter un membre" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "user", label: "Utilisateur" },
            { property: "category", label: "Fonction" },
            { property: "enable", label: "Actif ?" },
            { property: "since", label: "Depuis le" },
          ]
      form:
        title: "Ajouter/Modifier"
        fields:
          [
            {
              property: "user",
              label: "Utilisateur",
              type: "entity",
              type_options: { class: 'App\Entity\User' },
            },
            {
              property: "presentation",
              label: "Présentation",
              type: "fos_ckeditor",
            },
            {
              property: "category",
              label: "Fonction",
              type: "entity",
              type_options: { class: 'App\Entity\StaffCategory' },
            },
            { property: "enable", label: "Activé ?", type: "checkbox" },
            { property: "head_link", label: "Lien de la tête (skin)" },
            { property: "since", label: "Depuis le" },
            {
              property: "socialmedia",
              label: "Réseaux sociaux",
              type: "collection",
              type_options:
                {
                  entry_type: 'App\Form\UserSocialmediaType',
                  allow_delete: true,
                  allow_add: true,
                  by_reference: false,
                },
            },
          ]
