easy_admin:
  entities:
    Survey:
      class: App\Entity\Survey
      list:
        title: "Liste des sondages"
        actions:
          [
            { name: "show", label: "Détail", icon: "search" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "title", label: "Titre" },
            { property: "createdAt", label: "Créer le" },
            { property: "getLimitDate", label: "Jusqu'au", type: "datetime" },
            { property: "user", label: "Créer par" },
            { property: "countAnswers", label: "Nombre de réponses" },
          ]
      form: #create and edit
        title: "Liste des sondages"
        fields:
          [
            { property: "title", label: "Titre" },
            { property: "description", label: "Description" },
            {
              property: "answer_delay",
              label: "Temps de réponses maximale (en heures)",
            },
            {
              property: "answers_list",
              label: "Réponses possibles",
              type: "entity",
              type_options: { class: App\Entity\SurveyAnswerList },
            },
            {
              property: "createdAt",
              label: "Créer le",
              type_options: { disabled: true },
            },
          ]
