easy_admin:
  entities:
    SurveyAnswers:
      class: App\Entity\SurveyAnswers
      list:
        title: "Liste des réponses aux sondages"
        actions:
          [
            { name: "new", label: "Ajouter" },
            { name: "show", label: "Détail", icon: "search" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "id", label: "Id" },
            { property: "username", label: "Pseudonyme" },
            { property: "email", label: "input.email" },
            { property: "createdAt", label: "Créer le" },
            { property: "last_login", label: "Dernière connexion le" },
          ]
