easy_admin:
  entities:
    Survey:
      class: App\Entity\Survey
      list:
        title: "Liste des sondages"
        actions:
          [
            { name: "new", label: "Ajouter" },
            { name: "show", label: "Détail", icon: "search" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "title", label: "Titre" },
            { property: "fromTheDate", label: "Disponible dès le" },
            { property: "getLimitDate", label: "Jusqu'au", type: "datetime" },
            { property: "isEnable", label: "Actif ?", type: "boolean" },
            { property: "user", label: "Créer par" },
            { property: "countAnswers", label: "Réponses" },
            { property: "countTotalComments", label: "Commentaires" },
          ]
      form:
        title: "Ajouter/Modifier le sondage"
        fields:
          [
            { property: "title", label: "Titre" },
            {
              property: "slug",
              label: "Slug",
              help: "Url explicite pour le lien et SEO",
            },
            { property: "description", label: "Description", type: "fos_ckeditor" },
            {
              property: "answer_delay",
              label: "Temps de réponses maximale (en heures)",
            },
            {
              property: "answers_list",
              label: "Réponses possibles",
              type: "entity",
              type_options: { class: App\Entity\SurveyAnswerList },
            },
            { property: "fromTheDate", label: "Disponible dès le" },
          ]
      show:
        title: "Détail du sondage"
        fields:
          [
            { property: "title", label: "Titre" },
            { property: "slug", label: "Slug" },
            { property: "description", label: "Description" },
            {
              property: "answer_delay",
              label: "Temps de réponses maximale (en heures)",
            },
            {
              property: "fromTheDate",
              label: "Disponible dès le",
              type: "datetime",
            },
            { property: "getLimitDate", label: "Jusqu'au", type: "datetime" },
            { property: "isEnable", label: "Actif ?", type: "boolean" },
            {
              property: "countAnswersList",
              label: "Réponses possibles",
              type: "string",
            },
            {
              property: "countAnswers",
              label: "Nombre de réponses",
              type: "string",
            },
            {
              property: "countTotalComments",
              label: "Commentaires",
              type: "string",
            },
          ]
