easy_admin:
  entities:
    Thanks:
      class: App\Entity\Thanks
      list:
        title: "Liste des remerciements"
        actions:
          [
            { name: "new", label: "Ajouter un remerciement" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "user.username", label: "Pseudonyme" },
            { property: "thanks_category.name", label: "Catégorie" },
            { property: "createdAt", label: "Depuis le" },
          ]
      form:
        title: "Ajout du remerciement"
        fields:
          [
            {
              property: "user",
              label: "Utilisateur",
              type: "entity",
              type_options: { class: 'App\Entity\User' },
            },
            {
              property: "presentation",
              label: "Présentation",
              type: "textarea",
            },
            {
              property: "thanks_category",
              label: "Catégorie",
              type: "entity",
              type_options: { class: 'App\Entity\ThanksCategory' },
            },
            { property: "head_link", label: "Lien de la tête (skin)" },
            {
              property: "socialmedia",
              label: "Réseaux sociaux",
              type: "collection",
              type_options:
                {
                  entry_type: 'App\Form\UserSocialmediaType',
                  allow_delete: true,
                  allow_add: true,
                  by_reference: false,
                },
            },
          ]
