easy_admin:
  entities:
    Thanks:
      class: App\Entity\Thanks
      list:
        title: "Liste des remerciements"
        actions:
          [
            { name: "new", label: "Ajouter un remerciement" },
            { name: "show", label: "Détail", icon: "search" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "user.username", label: "Pseudonyme" },
            { property: "thanks_category.name", label: "Catégorie" },
            { property: "createdAt", label: "Depuis le" },
          ]
      show:
        title: "Information sur l'utilisateur"
        fields:
          [
            { property: "id", label: "Identification" },
            { property: "username", label: "Pseudonyme" },
            { property: "email", label: "input.email" },
            {
              property: "has_confirm_email",
              label: "Email confirmé ?",
              type: "boolean",
            },
            {
              property: "roles",
              label: "Roles",
              template: "easy_admin/fields/display_roles.html.twig",
            },
            { property: "createdAt", label: "Créer le" },
            { property: "last_login", label: "Dernière connexion le" },
          ]
      form:
        title: "Ajout du remerciement"
        fields:
          [
            {
              property: "user",
              label: "Utilisateur",
              type: "entity",
              type_options: { class: 'App\Entity\User' },
            },
            {
              property: "presentation",
              label: "Présentation",
              type: "textarea",
            },
            {
              property: "thanks_category",
              label: "Catégorie",
              type: "entity",
              type_options: { class: 'App\Entity\ThanksCategory' },
            },
            {
              property: "socialmedia",
              label: "Réseaux sociaux",
              type: "collection",
              type_options:
                {
                  entry_type: 'App\Form\UserSocialmediaType',
                  allow_delete: true,
                },
            },
          ]
