easy_admin:
  entities:
    ForumDiscussionStatus:
      class: App\Entity\ForumDiscussionStatus
      permissions:
        list: ["ROLE_MANAGEUR"]
        edit: ["ROLE_ADMIN"]
        new: ["ROLE_ADMIN"]
        delete: ["ROLE_ADMIN"]
        show: ["ROLE_STAFF"]
      list:
        title: "Liste des status pour les discussions"
        actions:
          [
            { name: "new", label: "Ajouter" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "status", label: "Status" },
            { property: "info", label: "Information" },
            { property: "color", label: "Couleur" },
          ]
      form:
        title: "Ajouter/Modifier"
        fields:
          [
            { property: "status", label: "Status" },
            { property: "info", label: "Information" },
            { property: "color", label: "Couleur", help: "Bootstrap badge class" },
          ]
