api_platform:
  # Enable the NelmioApiDocBundle integration.
  enable_nelmio_api_doc: false # Deprecated (Enabling the NelmioApiDocBundle integration has been deprecated in 2.2 and will be removed in 3.0. NelmioApiDocBundle 3 has native support for API Platform.)

  # Enable the Swagger documentation and export.
  enable_swagger: false

  # Enable Swagger UI
  enable_swagger_ui: false

  # Enable ReDoc
  enable_re_doc: false

  # Enable the entrypoint
  enable_entrypoint: false

  # Enable the docs
  enable_docs: false
