imports:
- { resource: DevProgression.yaml }
- { resource: SocialmediaType.yaml }
- { resource: MySocialmedia.yaml }
- { resource: FAQ.yaml }
- { resource: VoteSite.yaml }
- { resource: user/User.yaml }
- { resource: user/Staff.yaml }
- { resource: user/StaffCategory.yaml }
- { resource: user/Thanks.yaml }
- { resource: user/ThanksCategory.yaml }
- { resource: user/UserIp.yaml }
- { resource: user/UserVote.yaml }
- { resource: survey/Survey.yaml }
- { resource: logs/ActionLog.yaml }
- { resource: logs/ExceptionLog.yaml }
- { resource: survey/SurveyAnswerList.yaml }
- { resource: survey/SurveyAnswers.yaml }
- { resource: survey/SurveyComments.yaml }
- { resource: forum/ForumCategory.yaml }
- { resource: forum/ForumDiscussion.yaml }
- { resource: forum/ForumSubCategory.yaml }
- { resource: forum/ForumDiscussionAnswer.yaml }
- { resource: forum/ForumDiscussionStatus.yaml }
- { resource: spoil/Spoil.yaml }
- { resource: spoil/SpoilShare.yaml }
- { resource: spoil/SpoilGoalType.yaml }
- { resource: store/StoreCategory.yaml }
- { resource: store/StoreArticle.yaml }
- { resource: payment/PaymentTypes.yaml }