imports:
- { resource: ForumDiscussion.yaml }
- { resource: ForumCategory.yaml }
- { resource: User.yaml }
- { resource: DevProgression.yaml }
- { resource: Survey.yaml }
- { resource: SurveyAnswerList.yaml }
- { resource: SurveyAnswers.yaml }
- { resource: SurveyComments.yaml }
- { resource: Thanks.yaml }
- { resource: ThanksCategory.yaml }
- { resource: SocialmediaType.yaml }
- { resource: MySocialmedia.yaml }
- { resource: Staff.yaml }
- { resource: StaffCategory.yaml }
- { resource: FAQ.yaml }
- { resource: ForumSubCategory.yaml }
- { resource: ActionLog.yaml }
- { resource: ExceptionLog.yaml }
- { resource: UserIp.yaml }
- { resource: ForumDiscussionAnswer.yaml }
- { resource: ForumDiscussionStatus.yaml }
- { resource: Spoil.yaml }
- { resource: SpoilShare.yaml }
- { resource: SpoilGoalType.yaml }
- { resource: VoteSite.yaml }
- { resource: UserVote.yaml }
- { resource: store/StoreCategory.yaml }
- { resource: store/StoreArticle.yaml }