easy_admin:
  entities:
    ForumSubCategory:
      class: App\Entity\ForumSubCategory
      permissions:
        list: ["ROLE_STAFF"]
        edit: ["ROLE_ADMIN"]
        new: ["ROLE_ADMIN"]
        delete: ["ROLE_ADMIN"]
        show: ["ROLE_ADMIN"]
      list:
        title: "Liste des sous-catégories"
        actions:
          [
            { name: "new", label: "Ajouter" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "category", label: "Catégorie parente" },
            { property: "sub_title", label: "Sous-titre" },
            {
              property: "priority",
              label: "Ordre",
              template: "easy_admin/fields/integer.html.twig",
            },
            { property: "writable", label: "Ecrivable ?" },
            {
              property: "accept_staff_only",
              label: "Accept seulement le staff ?",
            },
            { property: "active", label: "Activé ?" },
            { property: "createdBy", label: "Créé par" },
            { property: "createdAt", label: "Créé le" },
            { property: "countDiscussion", label: "Discussions" },
            { property: "countMessages", label: "Messages" },
          ]
      form:
        title: "Ajouter/Modifier"
        fields:
          [
            { property: "name", label: "Nom" },
            {
              property: "category",
              label: "Catégorie parente",
              type: "entity",
              type_options:
                {
                  class: 'App\Entity\ForumCategory',
                  required: true,
                  multiple: false,
                  query_builder: 'App\Repository\ForumCategoryRepository::getMainCategoriesFromAdmin',
                },
            },
            { property: "description", label: "Description", type: "fos_ckeditor" },
            { property: "sub_title", label: "Sous-titre", help: "Sous-titre affiché depuis les catégories" },
            { property: "priority", label: "Ordre" },
            { property: "active", label: "Activé ?" },
            { property: "writable", label: "Ecrivable ?" },
            {
              property: "accept_staff_only",
              label: "Accept seulement le staff ?",
              help: "Le joueur peut créer la discussion que pour le staff ?",
            },
            {
              property: "slug",
              label: "Slug",
              help: "Url explicite pour le lien et SEO",
            },
          ]
