easy_admin:
  entities:
    ForumCategory:
      class: App\Entity\ForumCategory
      permissions:
        list: ["ROLE_ADMIN"]
        edit: ["ROLE_ADMIN"]
        new: ["ROLE_ADMIN"]
        delete: ["ROLE_ADMIN"]
        show: ["ROLE_ADMIN"]
      list:
        title: "Liste des catégories principales"
        actions:
          [
            { name: "new", label: "Ajouter" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "description", label: "Description" },
            {
              property: "priority",
              label: "Ordre",
              template: "easy_admin/fields/integer.html.twig",
            },
            { property: "active", label: "Activé ?" },
            { property: "createdBy", label: "Créé par" },
            { property: "createdAt", label: "Créé le" },
          ]
      form:
        title: "Ajouter/Modifier"
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "description", label: "Description" },
            { property: "priority", label: "Ordre" },
            { property: "active", label: "Activé ?" },
            {
              property: "slug",
              label: "Slug",
              help: "Url explicite pour le lien et SEO",
            },
          ]
