easy_admin:
  entities:
    SurveyAnswers:
      class: App\Entity\SurveyAnswers
      disabled_actions: ["new"]
      permissions:
        delete: ["ROLE_ADMIN"]
        new: ["ROLE_ADMIN"]
        edit: ["ROLE_ADMIN"]
        show: ["ROLE_ADMIN"]
      list:
        title: "Liste des réponses aux sondages"
        actions:
          [
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "survey", label: "Sondage" },
            { property: "user", label: "Utilisateur" },
            { property: "answer", label: "Réponse" },
            { property: "date", label: "Répondu le" },
          ]
