easy_admin:
  entities:
    ThanksCategory:
      class: App\Entity\ThanksCategory
      permissions:
        new: ["ROLE_ADMIN"]
        edit: ["ROLE_ADMIN"]
        delete: ["ROLE_ADMIN"]
      list:
        title: "Liste des catégories de remerciements"
        actions:
          [
            { name: "new", label: "Ajouter une Catégorie" },
            { name: "show", label: "Détail", icon: "search" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "subtitle", label: "Sous-titre" },
            { property: "description", label: "Description" },
            {
              property: "priority",
              label: "Priorité/Ordre",
              template: "easy_admin/fields/integer.html.twig",
            },
          ]
      show:
        title: "Information sur la catégorie"
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "subtitle", label: "Sous-titre" },
            { property: "description", label: "Description" },
          ]
      form:
        title: "Ajout du la catégorie"
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "subtitle", label: "Sous-titre" },
            { property: "description", label: "Description", type: "textarea" },
            {
              property: "priority",
              label: "Priorité/Ordre",
              template: "easy_admin/fields/integer.html.twig",
            },
          ]
