easy_admin:
  entities:
    User:
      class: App\Entity\User
      disabled_actions: ["new"]
      permissions:
        list: ["ROLE_MANAGEUR"]
        show: ["ROLE_MANAGEUR"]
        delete: ["ROLE_ADMIN"]
        edit: ["ROLE_ADMIN"]
      list:
        title: "Liste des joueurs inscrits"
        filters: [{ property: "roles", type: "array", label: "Roles" }]
        actions:
          [
            { name: "show", label: "Détail", icon: "search" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "username", label: "Pseudonyme" },
            {
              property: "email",
              label: "input.email",
              permission: "ROLE_ADMIN",
            },
            { property: "createdAt", label: "Créer le" },
            { property: "last_login", label: "Dernière connexion le" },
            {
              property: "has_confirm_email",
              label: "Email confirmée ?",
              type: "boolean",
            },
            { property: "countIPs", label: "Nombre d'IPs" },
          ]
      show:
        title: "Information sur l'utilisateur"
        fields:
          [
            { property: "id", label: "Identification" },
            { property: "username", label: "Pseudonyme" },
            {
              property: "email",
              label: "input.email",
              permission: "ROLE_ADMIN",
            },
            {
              property: "has_confirm_email",
              label: "Email confirmé ?",
              type: "boolean",
            },
            {
              property: "roles",
              label: "Roles",
              template: "easy_admin/fields/display_roles.html.twig",
            },
            { property: "createdAt", label: "Créer le" },
            { property: "last_login", label: "Dernière connexion le" },
            { property: "userIps", label: "Historique d'IPs" },
          ]
      form:
        item_permission: "ROLE_ADMIN"
        title: "Modifier l'utilisateur"
        fields:
          [
            { property: "username", label: "Pseudonyme" },
            { property: "email", label: "input.email" },
            {
              property: "roles",
              label: "Roles",
              type: "choice",
              type_options:
                {
                  expanded: true,
                  mapped: true,
                  multiple: true,
                  choices:
                    {
                      "Rôle utilisateur": "ROLE_USER",
                      "Launcher": "ROLE_LAUNCHER",
                      "Panel admin": "ROLE_PANEL_ADMIN",
                      "Helper": "ROLE_HELPEUR",
                      "Manager": "ROLE_MANAGEUR",
                      "Modérateur": "ROLE_MODERATEUR",
                      "Administrateur": "ROLE_ADMIN",
                    },
                },
            },
            {
              property: "has_confirm_email",
              type: "checkbox",
              label: "Email confirmé",
            },
          ]
