easy_admin:
  entities:
    VoteSite:
      class: App\Entity\VoteSite
      permissions:
        list: ["ROLE_ADMIN"]
        delete: ["ROLE_ADMIN"]
        edit: ["ROLE_ADMIN"]
        show: ["ROLE_ADMIN"]
        new: ["ROLE_ADMIN"]
      list:
        title: "Sites de vote"
        actions:
          [
            { name: "new", label: "Ajouter un site" },
            { name: "edit", label: "Modifier", icon: "edit" },
            { name: "delete", label: "Supprimer", icon: "trash" },
          ]
        fields:
          [
            { property: "name", label: "Nom" },
            { property: "createdAt", label: "Créér le" },
            { property: "active", label: "Actif" },
          ]
        form:
          title: "Ajouter/Modifier"
          fields: [{ property: "name", label: "Nom" }]
