easy_admin:
  design:
    menu:
      - label: "Utilisateurs"
        icon: "users-cog"
        children: [{ entity: "User", label: "Joueurs" }]
      - label: "Maintenance"
        icon: "tools"
        children: [{ entity: "DevProgression", label: "Progressions" }]
      - label: "Sondages"
        icon: "poll-h"
        children:
          [
            { entity: "Survey", label: "Sondages" },
            { entity: "SurveyAnswerList", label: "Listes réponses" },
            { entity: "SurveyAnswers", label: "Réponses" },
          ]
      - label: "Équipe"
        icon: "user-tie"
        children:
          [
            { entity: "Thanks", label: "Remerciements" },
            { entity: "ThanksCategory", label: "Remerciements catégories" },
          ]
      - label: "Réseaux sociaux"
        icon: "network-wired"
        children:
          [
            { entity: "SocialmediaType", label: "Liste" },
            { entity: "MySocialmedia", label: "ScandiCraft" },
          ]
      - { label: "liens" }
      - {
          label: "Retour",
          url: "/",
          icon: "chevron-circle-left",
          target: "_self",
        }
    assets:
      css:
        - "build/easy_admin.css"
  list:
    max_results: 50
  formats:
    datetime: "d/m/Y à H:i"
    date: d/m/Y
    time: "H:i"
    number: "%.3f"
