easy_admin:
  design:
    menu:
      - label: "Utilisateurs"
        icon: "users-cog"
        children: [{ entity: "User", label: "Joueurs" }]
      - label: "Maintenance"
        icon: "tools"
        permission: "ROLE_ADMIN"
        children: [{ entity: "DevProgression", label: "Progressions", permission: "ROLE_ADMIN" }]
      - label: "Forum"
        icon: "comments"
        permission: "ROLE_ADMIN"
        children:
          [
            { entity: "ForumCategory", label: "Categories" },
            { entity: "ForumSubCategory", label: "Sous-categories" },
          ]
      - label: "Sondages"
        icon: "poll-h"
        children:
          [
            { entity: "Survey", label: "Sondages" },
            { entity: "SurveyAnswers", label: "Réponses" },
            { entity: "SurveyComments", label: "Commentaires" },
            { entity: "SurveyAnswerList", label: "Listes réponses" },
          ]
      - label: "Équipe"
        icon: "user-tie"
        children:
          [
            { entity: "Staff", label: "Staff", permission: "ROLE_ADMIN" },
            { entity: "Thanks", label: "Remerciements" },
            { entity: "StaffCategory", label: "Staff catégories", permission: "ROLE_ADMIN" },
            { entity: "ThanksCategory", label: "Remerciements catégories" },
          ]
      - label: "Aide"
        icon: "hands-helping"
        children: [{ entity: "FAQ", label: "FAQ" }]
      - label: "Réseaux sociaux"
        icon: "network-wired"
        permission: "ROLE_ADMIN"
        children:
          [
            { entity: "SocialmediaType", label: "Liste", permission: "ROLE_ADMIN" },
            { entity: "MySocialmedia", label: "ScandiCraft", permission: "ROLE_ADMIN" },
          ]
      - { label: "liens" }
      - {
          label: "Retour",
          url: "/",
          icon: "chevron-circle-left",
          target: "_self",
        }
    assets:
      css:
        - "build/easy_admin.css"
  list:
    max_results: 50
  formats:
    datetime: "d/m/Y à H:i"
    date: d/m/Y
    time: "H:i"
    number: "%.3f"
